FROM python:2.7

RUN curl -Ls http://download.splunk.com/misc/packaging-toolkit/splunk-packaging-toolkit-1.0.0.tar.gz -o /tmp/slim.tar.gz && \
    pip install semantic_version && \
    pip install /tmp/slim.tar.gz

COPY ./signalfx-forwarder-app /code/signalfx-forwarder-app
WORKDIR /code

CMD slim package signalfx-forwarder-app
