---
version: 2.1

executors:
  python38:
    docker:
      - image: python:3.8
    working_directory: ~/repo

  machine_image:
    machine:
      image: ubuntu-1604:202007-01

commands:
  install_slim:
    steps:
      - restore_cache:
          key: v2-slim-venv-1.0.0
      - run:
          name: Install slim
          command: |
            pip install virtualenv
            if [ ! -d ~/slim ]; then
                curl -Ls http://download.splunk.com/misc/packaging-toolkit/splunk-packaging-toolkit-1.0.0.tar.gz -o /tmp/slim.tar.gz
                virtualenv --python=/usr/bin/python2.7 ~/slim
                source ~/slim/bin/activate
                pip install semantic_version
                pip install /tmp/slim.tar.gz
            fi
      - save_cache:
          key: v2-slim-venv-1.0.0
          paths:
            - ~/slim

  install_appinspect:
    steps:
      - run:
          name: Download appinspect
          command: curl -sSL https://download.splunk.com/misc/appinspect/splunk-appinspect-latest.tar.gz -o /tmp/appinspect.tar.gz
      - restore_cache:
          key: v1-appinspect-venv-{{ checksum "/tmp/appinspect.tar.gz" }}
      - run:
          name: Install appinspect
          command: |
            apt-get update
            apt-get install -y gcc libxml2-dev libxslt-dev lib32z1-dev python-lxml
            pip install virtualenv
            if [ ! -d ~/appinspect ]; then
                apt-get install -y python3.7-dev
                virtualenv --python=/usr/bin/python3.7 ~/appinspect
                source ~/appinspect/bin/activate
                pip install /tmp/appinspect.tar.gz
            fi
      - save_cache:
          key: v1-appinspect-venv-{{ checksum "/tmp/appinspect.tar.gz" }}
          paths:
            - ~/appinspect

  install_pytest:
    description: Install pytest and dependencies with pyenv
    parameters:
      python_version:
        type: string
        default: "3.8.0"
    steps:
      - restore_cache:
          key: v1-pytest-{{ checksum "tests/requirements.txt" }}-<< parameters.python_version >>
      - run:
          name: Install pytest and dependencies
          command: |
            cd $PYENV_ROOT && git pull && cd -
            pyenv install --skip-existing 3.8.0
            pyenv global 3.8.0
            if which pip; then
                pip install --upgrade 'pip==20.0.2'
            else
                curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
                python get-pip.py 'pip==20.0.2'
            fi
            pip install -r tests/requirements.txt
            pyenv rehash
      - save_cache:
          key: v1-pytest-{{ checksum "tests/requirements.txt" }}-<< parameters.python_version >>
          paths:
            - /opt/circleci/.pyenv

jobs:
  pylint:
    executor: python38
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            pip install -r tests/requirements.txt
            pip install pylint==2.5.3
      - run:
          name: Run pylint
          command: |
            pylint signalfx-forwarder-app/bin --ignore lib

  slim:
    executor: python38
    steps:
      - checkout
      - install_slim
      - run:
          name: Run slim
          command: |
            source ~/slim/bin/activate
            slim package --output /tmp/workspace ./signalfx-forwarder-app
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - signalfx-forwarder-*.tar.gz
      - store_artifacts:
          path: /tmp/workspace/

  appinspect:
    executor: python38
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - install_appinspect
      - run:
          name: Run appinspect
          command: |
            mkdir -p ~/testresults
            source ~/appinspect/bin/activate
            splunk-appinspect inspect /tmp/workspace/signalfx-forwarder-*.tar.gz --mode=precert --data-format junitxml --output-file ~/testresults/results.xml
            grep -q '<testsuite.*errors="0"' ~/testresults/results.xml || exit 1
            grep -q '<testsuite.*failures="0"' ~/testresults/results.xml || exit 1
      - store_test_results:
          path: ~/testresults
      - store_artifacts:
          path: ~/testresults

  integration_test:
    executor: machine_image
    parameters:
      version:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - install_pytest
      - run:
          name: Integration test
          environment:
            SPLUNK_VERSIONS: << parameters.version >>
          command: |
            mkdir -p /tmp/scratch
            cp /tmp/workspace/signalfx-forwarder-*.tar.gz .
            pytest --verbose --junitxml=~/testresults/results.xml --html=~/testresults/results.html --self-contained-html tests/splunk_test.py
      - store_test_results:
          path: ~/testresults
      - store_artifacts:
          path: ~/testresults

workflows:
  build_test:
    jobs:
      - pylint
      - slim
      - appinspect:
          requires:
            - slim
      - integration_test:
          name: splunk_6.5.0_test
          version: 6.5.0
          requires:
            - slim
      - integration_test:
          name: splunk_7.0.0_test
          version: 7.0.0
          requires:
            - slim
      - integration_test:
          name: splunk_8.0.0_test
          version: 8.0.0
          requires:
            - slim
      - integration_test:
          name: splunk_8.1.0_test
          version: 8.1.0-debian
          requires:
            - slim
